django-app/donations/urls.py
from django.urls import path

from donations import views
from donations.payment_gateways._2c2p.views import verify_2c2p_response, return_from_2c2p
from donations.payment_gateways.stripe.views import create_checkout_session, verify_stripe_response, return_from_stripe, cancel_from_stripe, return_from_stripe_card_update, cancel_from_stripe_card_update
from donations.payment_gateways.paypal.views import create_paypal_transaction, verify_paypal_response, capture_paypal_order, return_from_paypal, cancel_from_paypal, cancel_from_paypal_card_update, return_from_paypal_card_update
from donations.payment_gateways.paypal_legacy.views import verify_paypal_legacy_response

app_name = 'donations'
urlpatterns = [
    path('donate/', views.donate, name='donate'),
    path('register-signin/', views.register_signin, name='register-signin'),
    path('confirm-donation/', views.confirm_donation, name='confirm-donation'),
    # path('donation-details/', views.donation_details, name='donation-details'),
    path('edit-recurring/<int:id>/', views.edit_recurring, name='edit-recurring'),
    path('toggle-recurring/', views.toggle_recurring, name='toggle-recurring'),
    path('cancel-recurring/', views.cancel_recurring, name='cancel-recurring'),
    path('dismiss-warning/', views.dismiss_warning, name='dismiss-warning' ),
    # path('verify-2c2p-response/', verify_2c2p_response, name='verify-2c2p-response'),
    # path('return-from-2c2p/', return_from_2c2p, name='return-from-2c2p'),
    path('create-stripe-session/', create_checkout_session, name='create-stripe-session'),
    path('verify-stripe-response/', verify_stripe_response, name='verify-stripe-response'),
    path('return-from-stripe/', return_from_stripe, name='return-from-stripe'),
    path('return-from-stripe-card-update/', return_from_stripe_card_update, name='return-from-stripe-card-update'),
    path('cancel-from-stripe/', cancel_from_stripe, name='cancel-from-stripe'),
    path('cancel-from-stripe-card-update/', cancel_from_stripe_card_update, name='cancel-from-stripe-card-update'),
    path('create-paypal-transaction/', create_paypal_transaction, name='create-paypal-transaction'),
    path('return-from-paypal/', return_from_paypal, name='return-from-paypal'),
    path('return-from-paypal-card-update/', return_from_paypal_card_update, name='return-from-paypal-card-update'),
    path('cancel-from-paypal/', cancel_from_paypal, name='cancel-from-paypal'),
    path('cancel-from-paypal-card-update/', cancel_from_paypal_card_update, name='cancel-from-paypal-card-update'),
    path('verify-paypal-response/', verify_paypal_response, name='verify-paypal-response'),
    path('verify-paypal-legacy-response/', verify_paypal_legacy_response, name='verify-paypal-legacy-response'),
    path('thank-you/', views.thank_you, name='thank-you'),
    path('cancelled/', views.cancelled, name='cancelled'),
    path('revoked/', views.revoked, name='revoked'),
    path('my-onetime-donations/', views.my_onetime_donations, name='my-onetime-donations'),
    path('my-recurring-donations/', views.my_recurring_donations, name='my-recurring-donations'),
    path('my-renewals/<uuid:uuid>/', views.my_renewals, name='my-renewals'),
    path('confirm-update-card-details/<int:id>/', views.confirm_update_card_details, name='confirm-update-card-details'),
    path('export-donations/', views.export_donations, name='export-donations'),
    path('export-subscriptions', views.export_subscriptions, name='export-subscriptions'),
    path('export-donors/', views.export_donors, name='export-donors')
]

django-app/donations/payment_gateways/_2c2p/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt

from newstream.functions import _exception
from donations.models import STATUS_COMPLETE, STATUS_CANCELLED, STATUS_REVOKED
from donations.payment_gateways._2c2p.factory import Factory_2C2P
from .functions import map2C2PPaymentStatus


@csrf_exempt
def verify_2c2p_response(request):
    try:
        gatewayManager = Factory_2C2P.initGatewayByVerification(request)
        return gatewayManager.process_webhook_response()
    except ValueError as e:
        _exception(str(e))
        return HttpResponse(status=400)
    except RuntimeError as e:
        _exception(str(e))
        return HttpResponse(status=500)
    except Exception as e:
        _exception(str(e))
        return HttpResponse(status=500)


@csrf_exempt
def return_from_2c2p(request):
    try:
        gatewayManager = Factory_2C2P.initGatewayByReturn(request)
        request.session['return-donation-id'] = gatewayManager.donation.id
    
        if map2C2PPaymentStatus(gatewayManager.data['payment_status']) == STATUS_COMPLETE:
            return redirect('donations:thank-you')
        elif map2C2PPaymentStatus(gatewayManager.data['payment_status']) == STATUS_CANCELLED:
            return redirect('donations:cancelled')
        elif map2C2PPaymentStatus(gatewayManager.data['payment_status']) == STATUS_REVOKED:
            return redirect('donations:revoked')
        else:
            request.session['error-title'] = str(_("Unknown Error"))
            request.session['error-message'] = str(_(
                "Could not determine how to treat payment status: "+map2C2PPaymentStatus(gatewayManager.data['payment_status'])))
    except ValueError as e:
        _exception(str(e))
        request.session['error-title'] = str(_("ValueError"))
        request.session['error-message'] = str(e)
    except Exception as e:
        _exception(str(e))
        request.session['error-title'] = str(_("Unknown Error"))
        request.session['error-message'] = str(e)
    return redirect('donations:thank-you')

django-app/donations/payment_gateways/paypal/views.py
import json
import logging
logger = logging.getLogger('newstream')
from datetime import datetime, timezone
from django.shortcuts import redirect
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from paypalhttp import HttpError

from newstream.classes import WebhookNotProcessedError, WebhookMissingDonationIdError
from newstream.functions import object_to_json, _debug, _exception
from donations.models import Donation, STATUS_COMPLETE, STATUS_FAILED, STATUS_PAYMENT_FAILED, SubscriptionInstance, SubscriptionPaymentMeta
from donations.functions import removeSubscriptionWarnings
from donations.email_functions import sendDonationNotifToAdmins, sendDonationReceiptToDonor
from donations.payment_gateways.setting_classes import getPayPalSettings
from donations.payment_gateways import Factory_Paypal
from donations.payment_gateways.paypal.functions import create_paypal_order, capture_paypal_order, listProducts, createProduct, createPlan, createSubscription


def create_paypal_transaction(request):
    """ When the user reaches last step after confirming the donation,
        user is redirected via gatewayManager.redirect_to_gateway_url(), which renders redirection_paypal.html

        This function calls to PayPal Api to create a PayPal subscription object or PayPal order(one-time donation),
        then this function returns the approval_link to frontend js and to redirect to PayPal's checkout page

        Sample (JSON) request: {
            'csrfmiddlewaretoken': 'LZSpOsb364pn9R3gEPXdw2nN3dBEi7RWtMCBeaCse2QawCFIndu93fD3yv9wy0ij'
        }

        @todo: revise error handling, avoid catching all exceptions at the end
    """

    errorObj = {
        "issue": "Exception",
        "description": ""
    }
    result = {}
    try:
        paypalSettings = getPayPalSettings()

        donation_id = request.session.pop('donation_id', None)
        if not donation_id:
            raise ValueError(_("Missing donation_id in session"))
        donation = Donation.objects.get(pk=int(donation_id))

        if donation.is_recurring:
            # Product should have been created by admin manually at the dashboard/setup wizard
            # if no product exists, create one here(double safety net)
            # todo: make sure the product_id in site_settings has been set by some kind of configuration enforcement before site is launched
            product_list = listProducts(request.session)
            product = None
            if len(product_list['products']) == 0:
                product = createProduct(request.session)
            else:
                # get the product, should aim at the product with the specific product id
                for prod in product_list['products']:
                    if prod['id'] == paypalSettings.product_id:
                        product = prod
            if product == None:
                raise ValueError(_('Cannot initialize/get the paypal product object'))
            # Create plan and subscription
            plan = createPlan(request.session, product['id'], donation)
            if plan['status'] == 'ACTIVE':
                subscription = createSubscription(request, plan['id'], donation)
                result['subscription_id'] = subscription['id']
                for link in subscription['links']:
                    if link['rel'] == 'approve':
                        result['approval_link'] = link['href']
            else:
                raise ValueError(_("Newly created PayPal plan is not active, status: %(status)s") % {'status': plan['status']})
        # else: one-time donation
        else:
            response = create_paypal_order(request, donation)
            ppresult = response.result
            _debug('PayPal: Order Created Status: '+ppresult.status)
            # set approval_link attribute
            for link in ppresult.links:
                _debug('PayPal: --- {}: {} ---'.format(link.rel, link.href))
                if link.rel == 'approve':
                    result['approval_link'] = link.href
    except ValueError as e:
        _exception(str(e))
        errorObj['issue'] = "ValueError"
        errorObj['description'] = str(e)
        return JsonResponse(object_to_json(errorObj), status=500)
    except Donation.DoesNotExist:
        _exception("Donation.DoesNotExist")
        errorObj['issue'] = "Donation.DoesNotExist"
        errorObj['description'] = str(_("Donation object not found by id: %(id)s") % {'id': donation_id})
        return JsonResponse(object_to_json(errorObj), status=500)
    except HttpError as ioe:
        # Catching exceptions from the paypalclient execution, HttpError is a subclass of IOError
        httpError = json.loads(ioe.message)
        if 'details' in httpError and len(httpError['details']) > 0:
            errorObj["issue"] = httpError['details'][0]['issue']
            errorObj["description"] = httpError['details'][0]['description']
            _exception(errorObj["description"])
        # update donation status to failed
        donation.payment_status = STATUS_FAILED
        donation.save()
        return JsonResponse(object_to_json(errorObj), status=ioe.status_code)
    except Exception as error:
        errorObj['description'] = str(error)
        _exception(errorObj["description"])
        return JsonResponse(object_to_json(errorObj), status=500)
    return JsonResponse(object_to_json(result))


@csrf_exempt
def verify_paypal_response(request):
    """ This endpoint should be set as the listening endpoint for the webhook set in PayPal's developer dashboard(within a REST API App)
        The verification of the incoming PayPal requests is done via Factory_Paypal.initGatewayByVerification(request)
        The webhook should be set with the following events only:
            Billing subscription activated
            Billing subscription cancelled
            Billing subscription updated
            Payment capture completed
            Payment sale completed

        For more info on how to build this webhook endpoint, refer to PayPal documentation:
        https://developer.paypal.com/docs/subscriptions/integrate/

        @todo: revise error handling, avoid catching all exceptions at the end
    """

    try:
        # Set up gateway manager object with its linking donation, session, etc...
        gatewayManager = Factory_Paypal.initGatewayByVerification(request)

        if gatewayManager:
            return gatewayManager.process_webhook_response()
        else:
            raise Exception(_('gatewayManager for paypal not initialized.'))
    except WebhookNotProcessedError as error:
        # beware: this exception should be reserved for the incoming but not processed webhook events
        logger.info(str(error))
        # return 200 to prevent resending of paypal server of those requests
        return HttpResponse(status=200, reason=str(error))
    except WebhookMissingDonationIdError as error:
        if error.subscription_id in settings.PAYPAL_WEBHOOK_IGNORABLE_RESOURCES.split(','):
            log = "{}, but subscription id: {} is in list of PAYPAL_WEBHOOK_IGNORABLE_RESOURCES".format(error.message, error.subscription_id)
            logger.info(log)
            return HttpResponse(status=200, reason=log)
        else:
            log = "{}, subscription id: {}".format(error.message, error.subscription_id)
            logger.exception(log, exc_info=True)
            return HttpResponse(status=500, reason=log)
    except ValueError as error:
        _exception(str(error))
        return HttpResponse(status=500)
    except Exception as error:
        _exception(str(error))
        return HttpResponse(status=500)


@csrf_exempt
def return_from_paypal(request):
    """ This endpoint is submitted as the return_url when creating the PayPal SubscriptionInstance/Order at create_paypal_transaction(request)
        This url should receive GET params: 'token' and 'subscription_id'(only recurring payments); 'ba_token' is not used
        In Factory_PayPal.initGatewayByReturn(request), we save the subscription_id/token into the donationPaymentMeta data upon a successful request;
        exception will be raised if the endpoint is reached but a previous meta value is found,
        this is done to prevent this endpoint being called unlimitedly

        @todo: revise error handling, avoid catching all exceptions at the end
    """

    try:
        gatewayManager = Factory_Paypal.initGatewayByReturn(request)
        request.session['return-donation-id'] = gatewayManager.donation.id
        # subscription donation updates are handled by webhooks
        # returning from paypal only needs to deal with onetime donations
        if not gatewayManager.donation.is_recurring:
            # further capture payment if detected order approved, if not just set payment as processing and leave it to webhook processing
            if gatewayManager.order_status == 'APPROVED':
                # might raise IOError/HttpError
                capture_response = capture_paypal_order(gatewayManager.donation, gatewayManager.order_id)
                if capture_response.status == 'COMPLETED':
                    _debug('PayPal: Order Captured. Payment Completed.')
                    gatewayManager.donation.payment_status = STATUS_COMPLETE
                    gatewayManager.donation.donation_date = datetime.now(timezone.utc)
                    gatewayManager.donation.transaction_id = capture_response.purchase_units[0].payments.captures[0].id
                    gatewayManager.donation.save()
            else:
                _debug('PayPal: Order status after Paypal returns: '+gatewayManager.order_status)
        else:
            # save the subscription_id as profile_id
            gatewayManager.donation.subscription.profile_id = request.GET.get('subscription_id')

django-app/donations/payment_gateways/paypal_legacy/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from newstream.functions import _exception
from donations.payment_gateways import Factory_Paypal_Legacy


@csrf_exempt
def verify_paypal_legacy_response(request):
    try:
        # Set up gateway manager object with its linking donation, session, etc...
        gatewayManager = Factory_Paypal_Legacy.initGatewayByVerification(request)

        if gatewayManager:
            return gatewayManager.process_webhook_response()
        else:
            raise Exception(_('gatewayManager for paypal-legacy not initialized.'))
    except ValueError as error:
        _exception(str(error))
        return HttpResponse(status=500)
    except Exception as error:
        _exception(str(error))
        return HttpResponse(status=500)

django-app/donations/templates/modeladmin/donations/subscriptioninstance/index.html
{% extends "modeladmin/index.html" %}
{% load static common_tags i18n %}

{% block header_extra %}
    <div class="right">
        <div class="addbutton" style="margin-left: 2em;">
            <a href={% url 'donations:export-subscriptions'%} class="button bicolor icon icon-download">{% trans 'Subscriptions' %} CSV</a>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

django-app/donations/templates/modeladmin/donations/subscriptioninstance/inspect.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}

{% block titletag %}{{ view.get_meta_title }}{% endblock %}

{% block extra_css %}
<style>
    header {
        margin-bottom: 0 !important;
    }
    .content {
        padding-bottom: 0 !important;
    }
    .button.button-secondary {
        background-color: var(--w-color-surface-button-default);
        color: #ffffff;
    }
    .content-container {
        padding-bottom: 2rem; /* so that content doesn't get blocked by footer buttons */
    }
</style>
{{ block.super }}
{{ view.media.css }}
{% endblock %}

{% block extra_js %}
{{ block.super }}
{{ view.media.js }}
{% endblock %}

{% block content %}

{% block header %}
{% include "modeladmin/donations/components/breadcrumb.html"%}
{% include "wagtailadmin/shared/header.html" with title=view.get_page_title subtitle=view.get_page_subtitle icon=view.header_icon %}
{% endblock %}

<div class="content-container">
    {% block content_main %}
    <div class="backlink-div">
        <p class="back backlink-p">
            <a href="{{ view.index_url }}" class="icon icon-arrow-left">{% blocktrans with view.verbose_name as model_name %}Back to {{ model_name }} list{% endblocktrans %}</a>
        </p>
    </div>

    <div class="w-tabs" data-tabs>
        <div class="w-tabs__wrapper">
            <div role="tablist" class="w-tabs__list">
                {% include 'wagtailadmin/shared/tabs/tab_nav_link.html' with tab_id="subs-info" title=_("Subscription Info") %}
                {% include 'wagtailadmin/shared/tabs/tab_nav_link.html' with tab_id="meta-data" title=_("Meta Data") %}
                {% include 'wagtailadmin/shared/tabs/tab_nav_link.html' with tab_id="renewals" title=_("Renewals") %}
                {% include 'wagtailadmin/shared/tabs/tab_nav_link.html' with tab_id="actions" title=_("Actions") %}
                {% include 'wagtailadmin/shared/tabs/tab_nav_link.html' with tab_id="action-logs" title=_("Action Logs") %}
            </div>
        </div>

        <div class="tab-content">
            <section id="tab-subs-info" role="tabpanel" aria-labelledby="tab-label-subs-info" data-tab="subs-info" hidden>
                <div>
                    {% block fields_output %}
                    {% if fields %}
                    <div class="two-column-flex">
                        <div class="column-1-2">
                            <dt>{{ fields.is_test.label }}</dt>
                            <dd>{{ fields.is_test.value }}</dd>
                        </div>
                        <div class="column-1-2">
                            <dt>{{ fields.user.label }}</dt>
                            <dd>{{ fields.user.value }}</dd>
                        </div>
                    </div>
                    <div class="two-column-flex">
                        <div class="column-1-2">
                            <dt>{{ fields.recurring_amount.label }}</dt>
                            <dd>{{ fields.recurring_amount.value }}</dd>
                        </div>
                        <div class="column-1-2">
                            <dt>{{ fields.recurring_status.label }}</dt>
                            <dd>{{ fields.recurring_status.value }}</dd>
                        </div>
                    </div>
                    <div class="two-column-flex">
                        <div class="column-1-2">
                            <dt>{{ fields.currency.label }}</dt>
                            <dd>{{ fields.currency.value }}</dd>
                        </div>
                        <div class="column-1-2">
                            <dt>{{ fields.gateway.label }}</dt>
                            <dd>{{ fields.gateway.value }}</dd>
                        </div>
                    </div>
                    <div class="two-column-flex">
                        <div class="column-1-2">
                            <dt>{{ fields.id.label }}</dt>
                            <dd>{{ fields.id.value }}</dd>
                        </div>
                        <div class="column-1-2">
                            <dt>{{ fields.profile_id.label }}</dt>
                            <dd>{{ fields.profile_id.value }}</dd>
                        </div>
                    </div>
                    <div class="two-column-flex">
                        <div class="column-1-2">
                            <dt>{{ fields.created_at.label }}</dt>
                            <dd>{{ fields.created_at.value }}</dd>
                        </div>
                        <div class="column-1-2">
                            <dt>{{ fields.updated_at.label }}</dt>
                            <dd>{{ fields.updated_at.value }}</dd>
                        </div>
                    </div>
                    <div class="two-column-flex">
                        <div class="column-1-2">
                            <dt>{{ fields.linked_user_deleted.label }}</dt>
                            <dd>{{ fields.linked_user_deleted.value }}</dd>
                        </div>
                        {% if subscription.recurring_status == status_cancelled %}
                        <div class="column-1-2">
                            <dt>{{ fields.cancel_reason.label }}</dt>
                            <dd>{{ fields.cancel_reason.value }}</dd>
                        </div>
                        {% endif %}
                    </div>
                    {% endif %}
                    {% endblock %}
                </div>
            </section>
            <section id="tab-meta-data" role="tabpanel" aria-labelledby="tab-label-meta-data" data-tab="meta-data" hidden>
                <div>
                    {% if metas %}
                    <h2>{% trans 'System Generated Meta Data' %}</h2>
                    <dl>
                        {% for meta in metas %}
                        <dt>{{ meta.key }}</dt>
                        <dd>{{ meta.value }}</dd>
                        {% endfor %}
                    </dl>
                    {% else %}
                    <p>{% trans 'No system meta data registered.' %}</p>
                    {% endif %}
                </div>
            </section>
            <section id="tab-renewals" role="tabpanel" aria-labelledby="tab-label-renewals" data-tab="renewals" hidden>
                <div style="padding-bottom: 60px;">
                    {% if renewals %}
                    <table class="listing full-width">
                        <thead>
                            <tr>
                                <th>{% trans 'ID' %}</th>
                                <th>{% trans 'Transaction ID' %}</th>
                                <th>{% trans 'Donation amount' %}</th>
                                <th>{% trans 'Currency' %}</th>
                                <th>{% trans 'Payment status' %}</th>
                                <th>{% trans 'Donation date' %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for renewal in renewals %}
                            <tr>
                                <td>{{ renewal.id }} <a href="{% url 'donations_donation_modeladmin_inspect' instance_pk=renewal.id %}">(Inspect)</a></td>
                                <td>{{ renewal.transaction_id }}</td>
                                <td>{{ renewal.donation_amount }}</td>
                                <td>{{ renewal.currency }}</td>
                                <td>{{ renewal.payment_status }}</td>
                                <td>{{ renewal.donation_date }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <p>{% trans 'No renewals are found.' %}</p>
                    {% endif %}
                </div>
            </section>
            <section id="tab-actions" role="tabpanel" aria-labelledby="tab-label-actions" data-tab="actions" hidden>
                <div style="padding-bottom: 60px;">
                    <p>{% trans 'Current subscription status is:' %} <strong>{{ subscription.recurring_status|title }}</strong>.</p>
                    <hr>
                    <h2>{% trans 'Manually set subscription status' %}</h2>
                    <form action="{% url 'internal-set-subscription-status' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="id" id="admin-manual-set-status" value="{{fields.id.value}}">
                        <p>Set Subscription status as:</p>
                        <div class="col3" style="padding-left: 0px;">
                            <div class="dropdown dropdown-button match-width">
                                <input type="submit" name="status" value="{{ status_active|title }}" class="button">
                                <div class="dropdown-toggle icon icon-arrow-down"></div>
                                <ul>
                                    <li><input type="submit" name="status" value="{{ status_processing|title }}" class="button"></li>
                                    <li><input type="submit" name="status" value="{{ status_paused|title }}" class="button"></li>
                                    <li><input type="submit" name="status" value="{{ status_cancelled|title }}" class="button"></li>
                                    <li><input type="submit" name="status" value="{{ status_inactive|title }}" class="button"></li>
                                    <li><input type="submit" name="status" value="{{ status_payment_failed|title }}" class="button"></li>
                                </ul>
                            </div>
                        </div>
                        <div style="clear: both;"></div>
                    </form>
                    <hr>
                    {% if gateway_togglesub_supported %}
                    <h2>{% trans 'Toggle subscription status' %}</h2>
                    {% if subscription.recurring_status == status_active or subscription.recurring_status == status_paused %}
                    <form action="{% url 'internal-toggle-subscription' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{fields.id.value}}">
                        <input type="submit" class="button" id="admin-toggle-sub" value="{% if subscription.recurring_status == status_active %}{% trans 'Pause Subscription' %}{% else %}{% trans 'Resume Subscription' %}{% endif %}">
                        <br>
                        <small class="caution-text">*This action communicates with the payment gateway*</small>
                    </form>
                    {% else %}
                    <p>{% trans 'Subscription is not in a valid state for resuming/pausing.' %}</p>
                    {% endif %}
                    <hr>
                    {% else %}
                    <p>{% trans 'Toggle Subscription is not supported for this gateway.' %}</p>
                    <hr>
                    {% endif %}
                    {% if gateway_cancelsub_supported %}
                    <h2>{% trans 'Cancel subscription status' %}</h2>
                    {% if subscription.recurring_status != status_cancelled %}
                    <form action="{% url 'internal-cancel-subscription' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{fields.id.value}}">
                        <input type="submit" class="button" id="admin-cancel-sub" value="{% trans 'Cancel Subscription' %}">
                        <br>
                        <small class="caution-text">*This action communicates with the payment gateway*</small>
                    </form>
                    {% else %}
                    <p>{% trans 'Subscription is already cancelled.' %}</p>
                    {% endif %}
                    {% else %}
                    <p>{% trans 'Cancel Subscription is not supported for this gateway.' %}</p>
                    {% endif %}
                </div>
            </section>
            <section id="tab-action-logs" role="tabpanel" aria-labelledby="tab-label-action-logs" data-tab="action-logs" hidden>
                <div>
                    {% if action_logs %}
                    <table class="listing full-width">
                        <thead>
                            <tr>
                                <th>{% trans 'User' %}</th>
                                <th>{% trans 'Action type' %}</th>
                                <th>{% trans 'Action notes' %}</th>
                                <th>{% trans 'Created at' %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for log in action_logs %}
                            <tr>
                                <td>{{ log.user }}</td>
                                <td>{{ log.action_type }}</td>
                                <td>{{ log.action_notes }}</td>
                                <td>{{ log.created_at }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <p>{% trans 'No update-actions are logged.' %}</p>
                    {% endif %}
                </div>
            </section>
        </div>
    </div>
    {% endblock %}
</div>

{% block footer %}
    {% if buttons %}
        <footer class="footer">
            <div class="footer__container">
                {% for button in buttons %}
                    {% include "modeladmin/includes/button.html" %}
                {% endfor %}
            </div>
        </footer>
    {% endif %}
{% endblock %}
{% endblock %}