django-app/donations/urls.py
from django.urls import path

from donations import views
from donations.payment_gateways._2c2p.views import verify_2c2p_response, return_from_2c2p
from donations.payment_gateways.stripe.views import create_checkout_session, verify_stripe_response, return_from_stripe, cancel_from_stripe, return_from_stripe_card_update, cancel_from_stripe_card_update
from donations.payment_gateways.paypal.views import create_paypal_transaction, verify_paypal_response, capture_paypal_order, return_from_paypal, cancel_from_paypal, cancel_from_paypal_card_update, return_from_paypal_card_update
from donations.payment_gateways.paypal_legacy.views import verify_paypal_legacy_response

app_name = 'donations'
urlpatterns = [
    path('donate/', views.donate, name='donate'),
    path('register-signin/', views.register_signin, name='register-signin'),
    path('confirm-donation/', views.confirm_donation, name='confirm-donation'),
    # path('donation-details/', views.donation_details, name='donation-details'),
    path('edit-recurring/<int:id>/', views.edit_recurring, name='edit-recurring'),
    path('toggle-recurring/', views.toggle_recurring, name='toggle-recurring'),
    path('cancel-recurring/', views.cancel_recurring, name='cancel-recurring'),
    path('dismiss-warning/', views.dismiss_warning, name='dismiss-warning' ),
    # path('verify-2c2p-response/', verify_2c2p_response, name='verify-2c2p-response'),
    # path('return-from-2c2p/', return_from_2c2p, name='return-from-2c2p'),
    path('create-stripe-session/', create_checkout_session, name='create-stripe-session'),
    path('verify-stripe-response/', verify_stripe_response, name='verify-stripe-response'),
    path('return-from-stripe/', return_from_stripe, name='return-from-stripe'),
    path('return-from-stripe-card-update/', return_from_stripe_card_update, name='return-from-stripe-card-update'),
    path('cancel-from-stripe/', cancel_from_stripe, name='cancel-from-stripe'),
    path('cancel-from-stripe-card-update/', cancel_from_stripe_card_update, name='cancel-from-stripe-card-update'),
    path('create-paypal-transaction/', create_paypal_transaction, name='create-paypal-transaction'),
    path('return-from-paypal/', return_from_paypal, name='return-from-paypal'),
    path('return-from-paypal-card-update/', return_from_paypal_card_update, name='return-from-paypal-card-update'),
    path('cancel-from-paypal/', cancel_from_paypal, name='cancel-from-paypal'),
    path('cancel-from-paypal-card-update/', cancel_from_paypal_card_update, name='cancel-from-paypal-card-update'),
    path('verify-paypal-response/', verify_paypal_response, name='verify-paypal-response'),
    path('verify-paypal-legacy-response/', verify_paypal_legacy_response, name='verify-paypal-legacy-response'),
    path('thank-you/', views.thank_you, name='thank-you'),
    path('cancelled/', views.cancelled, name='cancelled'),
    path('revoked/', views.revoked, name='revoked'),
    path('my-onetime-donations/', views.my_onetime_donations, name='my-onetime-donations'),
    path('my-recurring-donations/', views.my_recurring_donations, name='my-recurring-donations'),
    path('my-renewals/<uuid:uuid>/', views.my_renewals, name='my-renewals'),
    path('confirm-update-card-details/<int:id>/', views.confirm_update_card_details, name='confirm-update-card-details'),
    path('export-donations/', views.export_donations, name='export-donations'),
    path('export-subscriptions', views.export_subscriptions, name='export-subscriptions'),
    path('export-donors/', views.export_donors, name='export-donors')
]

django-app/donations/payment_gateways/_2c2p/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt

from newstream.functions import _exception
from donations.models import STATUS_COMPLETE, STATUS_CANCELLED, STATUS_REVOKED
from donations.payment_gateways._2c2p.factory import Factory_2C2P
from .functions import map2C2PPaymentStatus


@csrf_exempt
def verify_2c2p_response(request):
    try:
        gatewayManager = Factory_2C2P.initGatewayByVerification(request)
        return gatewayManager.process_webhook_response()
    except ValueError as e:
        _exception(str(e))
        return HttpResponse(status=400)
    except RuntimeError as e:
        _exception(str(e))
        return HttpResponse(status=500)
    except Exception as e:
        _exception(str(e))
        return HttpResponse(status=500)


@csrf_exempt
def return_from_2c2p(request):
    try:
        gatewayManager = Factory_2C2P.initGatewayByReturn(request)
        request.session['return-donation-id'] = gatewayManager.donation.id
    
        if map2C2PPaymentStatus(gatewayManager.data['payment_status']) == STATUS_COMPLETE:
            return redirect('donations:thank-you')
        elif map2C2PPaymentStatus(gatewayManager.data['payment_status']) == STATUS_CANCELLED:
            return redirect('donations:cancelled')
        elif map2C2PPaymentStatus(gatewayManager.data['payment_status']) == STATUS_REVOKED:
            return redirect('donations:revoked')
        else:
            request.session['error-title'] = str(_("Unknown Error"))
            request.session['error-message'] = str(_(
                "Could not determine how to treat payment status: "+map2C2PPaymentStatus(gatewayManager.data['payment_status'])))
    except ValueError as e:
        _exception(str(e))
        request.session['error-title'] = str(_("ValueError"))
        request.session['error-message'] = str(e)
    except Exception as e:
        _exception(str(e))
        request.session['error-title'] = str(_("Unknown Error"))
        request.session['error-message'] = str(e)
    return redirect('donations:thank-you')

django-app/donations/payment_gateways/paypal/views.py
import json
import logging
logger = logging.getLogger('newstream')
from datetime import datetime, timezone
from django.shortcuts import redirect
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from paypalhttp import HttpError

from newstream.classes import WebhookNotProcessedError, WebhookMissingDonationIdError
from newstream.functions import object_to_json, _debug, _exception
from donations.models import Donation, STATUS_COMPLETE, STATUS_FAILED, STATUS_PAYMENT_FAILED, SubscriptionInstance, SubscriptionPaymentMeta
from donations.functions import removeSubscriptionWarnings
from donations.email_functions import sendDonationNotifToAdmins, sendDonationReceiptToDonor
from donations.payment_gateways.setting_classes import getPayPalSettings
from donations.payment_gateways import Factory_Paypal
from donations.payment_gateways.paypal.functions import create_paypal_order, capture_paypal_order, listProducts, createProduct, createPlan, createSubscription


def create_paypal_transaction(request):
    """ When the user reaches last step after confirming the donation,
        user is redirected via gatewayManager.redirect_to_gateway_url(), which renders redirection_paypal.html

        This function calls to PayPal Api to create a PayPal subscription object or PayPal order(one-time donation),
        then this function returns the approval_link to frontend js and to redirect to PayPal's checkout page

        Sample (JSON) request: {
            'csrfmiddlewaretoken': 'LZSpOsb364pn9R3gEPXdw2nN3dBEi7RWtMCBeaCse2QawCFIndu93fD3yv9wy0ij'
        }

        @todo: revise error handling, avoid catching all exceptions at the end
    """

    errorObj = {
        "issue": "Exception",
        "description": ""
    }
    result = {}
    try:
        paypalSettings = getPayPalSettings()

        donation_id = request.session.pop('donation_id', None)
        if not donation_id:
            raise ValueError(_("Missing donation_id in session"))
        donation = Donation.objects.get(pk=int(donation_id))

        if donation.is_recurring:
            # Product should have been created by admin manually at the dashboard/setup wizard
            # if no product exists, create one here(double safety net)
            # todo: make sure the product_id in site_settings has been set by some kind of configuration enforcement before site is launched
            product_list = listProducts(request.session)
            product = None
            if len(product_list['products']) == 0:
                product = createProduct(request.session)
            else:
                # get the product, should aim at the product with the specific product id
                for prod in product_list['products']:
                    if prod['id'] == paypalSettings.product_id:
                        product = prod
            if product == None:
                raise ValueError(_('Cannot initialize/get the paypal product object'))
            # Create plan and subscription
            plan = createPlan(request.session, product['id'], donation)
            if plan['status'] == 'ACTIVE':
                subscription = createSubscription(request, plan['id'], donation)
                result['subscription_id'] = subscription['id']
                for link in subscription['links']:
                    if link['rel'] == 'approve':
                        result['approval_link'] = link['href']
            else:
                raise ValueError(_("Newly created PayPal plan is not active, status: %(status)s") % {'status': plan['status']})
        # else: one-time donation
        else:
            response = create_paypal_order(request, donation)
            ppresult = response.result
            _debug('PayPal: Order Created Status: '+ppresult.status)
            # set approval_link attribute
            for link in ppresult.links:
                _debug('PayPal: --- {}: {} ---'.format(link.rel, link.href))
                if link.rel == 'approve':
                    result['approval_link'] = link.href
    except ValueError as e:
        _exception(str(e))
        errorObj['issue'] = "ValueError"
        errorObj['description'] = str(e)
        return JsonResponse(object_to_json(errorObj), status=500)
    except Donation.DoesNotExist:
        _exception("Donation.DoesNotExist")
        errorObj['issue'] = "Donation.DoesNotExist"
        errorObj['description'] = str(_("Donation object not found by id: %(id)s") % {'id': donation_id})
        return JsonResponse(object_to_json(errorObj), status=500)
    except HttpError as ioe:
        # Catching exceptions from the paypalclient execution, HttpError is a subclass of IOError
        httpError = json.loads(ioe.message)
        if 'details' in httpError and len(httpError['details']) > 0:
            errorObj["issue"] = httpError['details'][0]['issue']
            errorObj["description"] = httpError['details'][0]['description']
            _exception(errorObj["description"])
        # update donation status to failed
        donation.payment_status = STATUS_FAILED
        donation.save()
        return JsonResponse(object_to_json(errorObj), status=ioe.status_code)
    except Exception as error:
        errorObj['description'] = str(error)
        _exception(errorObj["description"])
        return JsonResponse(object_to_json(errorObj), status=500)
    return JsonResponse(object_to_json(result))


@csrf_exempt
def verify_paypal_response(request):
    """ This endpoint should be set as the listening endpoint for the webhook set in PayPal's developer dashboard(within a REST API App)
        The verification of the incoming PayPal requests is done via Factory_Paypal.initGatewayByVerification(request)
        The webhook should be set with the following events only:
            Billing subscription activated
            Billing subscription cancelled
            Billing subscription updated
            Payment capture completed
            Payment sale completed

        For more info on how to build this webhook endpoint, refer to PayPal documentation:
        https://developer.paypal.com/docs/subscriptions/integrate/

        @todo: revise error handling, avoid catching all exceptions at the end
    """

    try:
        # Set up gateway manager object with its linking donation, session, etc...
        gatewayManager = Factory_Paypal.initGatewayByVerification(request)

        if gatewayManager:
            return gatewayManager.process_webhook_response()
        else:
            raise Exception(_('gatewayManager for paypal not initialized.'))
    except WebhookNotProcessedError as error:
        # beware: this exception should be reserved for the incoming but not processed webhook events
        logger.info(str(error))
        # return 200 to prevent resending of paypal server of those requests
        return HttpResponse(status=200, reason=str(error))
    except WebhookMissingDonationIdError as error:
        if error.subscription_id in settings.PAYPAL_WEBHOOK_IGNORABLE_RESOURCES.split(','):
            log = "{}, but subscription id: {} is in list of PAYPAL_WEBHOOK_IGNORABLE_RESOURCES".format(error.message, error.subscription_id)
            logger.info(log)
            return HttpResponse(status=200, reason=log)
        else:
            log = "{}, subscription id: {}".format(error.message, error.subscription_id)
            logger.exception(log, exc_info=True)
            return HttpResponse(status=500, reason=log)
    except ValueError as error:
        _exception(str(error))
        return HttpResponse(status=500)
    except Exception as error:
        _exception(str(error))
        return HttpResponse(status=500)


@csrf_exempt
def return_from_paypal(request):
    """ This endpoint is submitted as the return_url when creating the PayPal SubscriptionInstance/Order at create_paypal_transaction(request)
        This url should receive GET params: 'token' and 'subscription_id'(only recurring payments); 'ba_token' is not used
        In Factory_PayPal.initGatewayByReturn(request), we save the subscription_id/token into the donationPaymentMeta data upon a successful request;
        exception will be raised if the endpoint is reached but a previous meta value is found,
        this is done to prevent this endpoint being called unlimitedly

        @todo: revise error handling, avoid catching all exceptions at the end
    """

    try:
        gatewayManager = Factory_Paypal.initGatewayByReturn(request)
        request.session['return-donation-id'] = gatewayManager.donation.id
        # subscription donation updates are handled by webhooks
        # returning from paypal only needs to deal with onetime donations
        if not gatewayManager.donation.is_recurring:
            # further capture payment if detected order approved, if not just set payment as processing and leave it to webhook processing
            if gatewayManager.order_status == 'APPROVED':
                # might raise IOError/HttpError
                capture_response = capture_paypal_order(gatewayManager.donation, gatewayManager.order_id)
                if capture_response.status == 'COMPLETED':
                    _debug('PayPal: Order Captured. Payment Completed.')
                    gatewayManager.donation.payment_status = STATUS_COMPLETE
                    gatewayManager.donation.donation_date = datetime.now(timezone.utc)
                    gatewayManager.donation.transaction_id = capture_response.purchase_units[0].payments.captures[0].id
                    gatewayManager.donation.save()
            else:
                _debug('PayPal: Order status after Paypal returns: '+gatewayManager.order_status)
        else:
            # save the subscription_id as profile_id
            gatewayManager.donation.subscription.profile_id = request.GET.get('subscription_id')

django-app/donations/payment_gateways/paypal_legacy/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from newstream.functions import _exception
from donations.payment_gateways import Factory_Paypal_Legacy


@csrf_exempt
def verify_paypal_legacy_response(request):
    try:
        # Set up gateway manager object with its linking donation, session, etc...
        gatewayManager = Factory_Paypal_Legacy.initGatewayByVerification(request)

        if gatewayManager:
            return gatewayManager.process_webhook_response()
        else:
            raise Exception(_('gatewayManager for paypal-legacy not initialized.'))
    except ValueError as error:
        _exception(str(error))
        return HttpResponse(status=500)
    except Exception as error:
        _exception(str(error))
        return HttpResponse(status=500)

django-app/donations/templates/donations/email_templates/account_deleted_admin.html
{% extends "base_email.html" %}
{% load common_tags i18n %}

{% block title %}
{{ mail_title }}
{% endblock %}

{% block content %}
<p style="{{ 'parag'|email_css }}">{% trans 'Hi Admins,' %}</p>
              
<p style="{{ 'parag'|email_css }}">{% trans 'This email is to inform you that a donor account has been deleted on your website:' %}</p>

<p style="{{ 'parag'|email_css }}">
    <a href="{% site_url %}/admin/users/" target="_blank" rel="noopener noreferrer">{% site_url %}/admin/users/</a>
</p>
                
<table cellpadding="8" style="margin-bottom: 30px;">
    <tr>
        <td style="font-weight: bold;">{% trans 'Donor name' %}</td>
        <td>{{ user.display_fullname }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans 'Donor email' %}</td>
        <td>{{ user.email }}</td>
    </tr>
</table>

<p style="{{ 'parag'|email_css }}">{% trans "Thank you," %}</p>

<p style="{{ 'parag'|email_css }}">{{ 'short_org_name'|site_settings }}</p>
{% endblock %}

django-app/donations/templates/donations/email_templates/donation_status_change.html
{% extends "base_email.html" %}
{% load common_tags donation_tags i18n %}

{% block title %}
{{ mail_title }}
{% endblock %}

{% block content %}
<p style="{{ 'parag'|email_css }}">{% trans "Dear" %} {{ donation.donor_name }},</p>
{% if donation.is_recurring %}
{% url 'donations:my-renewals' donation.subscription.parent.uuid as donations_url %}
{% else %}
{% url 'donations:my-onetime-donations' as donations_url %}
{% endif %}
{% if donation.user %}
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with donations_full_url=donations_url|site_rel_url %}Sign into our support page to <a href="{{donations_full_url}}" target="_blank" rel="noopener noreferrer">view your updated donation</a>.{% endblocktrans %}
</p>
{% endif %}
<p style="{{ 'parag'|email_css }}">{% trans "Details of your donation:" %}</p>
<table cellpadding="8" style="margin-bottom: 30px;">
    <tr>
        <td style="font-weight: bold;">{% trans "Transaction ID" %}</td>
        <td>{{ donation.transaction_id }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Donation frequency" %}</td>
        <td>{{ donation.donation_frequency }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Payment method" %}</td>
        <td>{{ donation|display_gateway }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Donation amount" %}</td>
        <td>{{ donation|amount_with_currency }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Payment status" %}</td>
        <td>{{ donation.payment_status|title }}</td>
    </tr>
</table>
<p style="{{ 'parag'|email_css }}">{% trans "Thank you," %}</p>

<p style="{{ 'parag'|email_css }}">{{ 'short_org_name'|site_settings }}</p>
{% endblock %}

django-app/donations/templates/donations/email_templates/recurring_failed_donor.html
{% extends "base_email.html" %}
{% load common_tags donation_tags i18n %}

{% block title %}
{{ mail_title }}
{% endblock %}

{% block content %}
<p style="{{ 'parag'|email_css }}">{% trans "Hi" %} {{ subscription.user.display_fullname }},</p>
{% url 'donations:my-recurring-donations' as donations_url %}
{% url "donations:confirm-update-card-details" subscription.id as update_payment_method_url %}
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with donation_amount=subscription|recurring_amount_with_currency %}Your recent <strong>{{ donation_amount }}</strong> recurring payment was <strong>unsuccessful</strong>{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with gateway=subscription.gateway %}{{gateway}} was unable to charge your account using your current existing payment method. Please update your payment information to complete your donation{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with update_payment_method_full_url=update_payment_method_url|site_rel_url%}<a href="{{update_payment_method_full_url}}" target="_blank" rel="noopener noreferrer">Update payment method</a>{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with org_contact_email='org_contact_email'|site_settings %}Please contact us at <a href="mailto:{{ org_contact_email }}">{{ org_contact_email }}</a> for any enquiries.{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">{% trans "Thank you," %}</p>

<p style="{{ 'parag'|email_css }}">{{ 'short_org_name'|site_settings }}</p>
{% endblock %}

django-app/donations/templates/donations/email_templates/recurring_resumed_donor.html
{% extends "base_email.html" %}
{% load common_tags donation_tags i18n %}

{% block title %}
{{ mail_title }}
{% endblock %}

{% block content %}
<p style="{{ 'parag'|email_css }}">{% trans "Dear" %} {{ subscription.user.display_fullname }},</p>
{% url 'donations:my-recurring-donations' as donations_url %}
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with donation_amount=subscription|recurring_amount_with_currency %}A big "thank you" for resuming your <strong>{{ donation_amount }}</strong> donation - it is very much appreciated and it will go a long way in supporting our operations. Recurring donations, in particular, are vital to our sustainability.{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans %}We are the city’s only independent English-language newspaper - run by journalists, backed by readers - no investors, shareholders or tycoons involved. Please check out <a href="https://hongkongfp.com/annual-report/" target="_blank" rel="noopener noreferrer">HKFP's latest Annual Report</a> - it includes our <a href="https://hongkongfp.com/transparency/" target="_blank" rel="noopener noreferrer">yearly, audited Transparency Report</a> - so you can see how carefully we spend our income.{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with donations_full_url=donations_url|site_rel_url org_contact_email='org_contact_email'|site_settings %}Sign into our support page to <a href="{{donations_full_url}}" target="_blank" rel="noopener noreferrer">adjust, pause or cancel your donation</a>. Please email <a href="mailto:{{ org_contact_email }}">{{ org_contact_email }}</a> if you have any further enquiries.{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans %}We are grateful to the minority of readers who help keep HKFP free to access for everyone. From all of us, <strong>thank you</strong> for helping keep independent media alive in Hong Kong!{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">{% trans "Details of your recurring donation:" %}</p>
<table cellpadding="8" style="margin-bottom: 30px;">
    <tr>
        <td style="font-weight: bold;">{% trans 'Donor name' %}</td>
        <td>{{ subscription.user.display_fullname }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Recurring donation identifier" %}</td>
        <td>{{ subscription.profile_id }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Payment method" %}</td>
        <td>{{ subscription|display_gateway }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Recurring donation amount" %}</td>
        <td>{{ subscription|recurring_amount_with_currency }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans 'Recurring donation status' %}</td>
        <td>{{ subscription.recurring_status|title }}</td>
    </tr>
</table>
<p style="{{ 'parag'|email_css }}">{% trans "Thank you," %}</p>

<p style="{{ 'parag'|email_css }}">{{ 'short_org_name'|site_settings }}</p>
{% endblock %}

django-app/donations/templates/donations/email_templates/renewal_receipt.html
{% extends "base_email.html" %}
{% load common_tags donation_tags i18n %}

{% block title %}
{% trans 'NEW RENEWAL DONATION' %}
{% endblock %}

{% block content %}
<p style="{{ 'parag'|email_css }}">{% trans "Dear" %} {{ donation.user.display_fullname }},</p>
{% url 'donations:my-renewals' donation.subscription.parent.uuid as renewals_url %}
{% url 'donations:my-recurring-donations' as donation_url %}
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with donation_amount=donation|amount_with_currency %}A big "thank you" for your kind <strong>{{ donation_amount }}</strong> recurring donation - it is very much appreciated and it will go a long way in supporting our operations.{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans %}We are the city’s only independent English-language newspaper - run by journalists, backed by readers - no investors, shareholders or tycoons involved. Please check out <a href="https://hongkongfp.com/annual-report/" target="_blank" rel="noopener noreferrer">HKFP's latest Annual Report</a> - it includes our <a href="https://hongkongfp.com/transparency/" target="_blank" rel="noopener noreferrer">yearly, audited Transparency Report</a> - so you can see how carefully we spend our income.{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with renewals_full_url=renewals_url|site_rel_url donation_full_url=donation_url|site_rel_url org_contact_email='org_contact_email'|site_settings %}Sign into our support page to <a href="{{renewals_full_url}}" target="_blank" rel="noopener noreferrer">view your renewal donations</a>. You can also <a href="{{donation_full_url}}" target="_blank" rel="noopener noreferrer">adjust, pause or cancel your recurring donation</a>. Please email <a href="mailto:{{ org_contact_email }}">{{ org_contact_email }}</a> if you have any further enquiries.{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans %}We are grateful to the minority of readers who help keep HKFP free to access for everyone. From all of us, <strong>thank you</strong> for helping keep independent media alive in Hong Kong!{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">{% trans "Details of your donation:" %}</p>
<table cellpadding="8" style="margin-bottom: 30px;">
    <tr>
        <td style="font-weight: bold;">{% trans "Transaction ID" %}</td>
        <td>{{ donation.transaction_id }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Donation frequency" %}</td>
        <td>{{ donation.donation_frequency }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Payment method" %}</td>
        <td>{{ donation|display_gateway }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Donation amount" %}</td>
        <td>{{ donation|amount_with_currency }}</td>
    </tr>
    <tr>
        <td style="font-weight: bold;">{% trans "Payment status" %}</td>
        <td>{{ donation.payment_status|title }}</td>
    </tr>
    {% if donation.is_recurring %}
    <tr>
        <td style="font-weight: bold;">{% trans 'Recurring donation status' %}</td>
        <td>{{ donation.subscription.recurring_status|title }}</td>
    </tr>
    {% endif %}
</table>
<p style="{{ 'parag'|email_css }}">{% trans "Thank you," %}</p>

<p style="{{ 'parag'|email_css }}">{{ 'short_org_name'|site_settings }}</p>
{% endblock %}

django-app/donations/templates/donations/email_templates/subscription_failed_donor.html
{% extends "base_email.html" %}
{% load common_tags donation_tags i18n %}

{% block title %}
{{ mail_title }}
{% endblock %}

{% block content %}
<p style="{{ 'parag'|email_css }}">{% trans "Hi" %} {{ subscription.user.display_fullname }},</p>
{% url 'donations:my-recurring-donations' as donations_url %}
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with donation_amount=subscription|recurring_amount_with_currency %}Your recent <strong>{{ donation_amount }}</strong> recurring payment was <strong>unsuccessful</strong>{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with gateway=subscription.gateway %}{{gateway}} was unable to charge your account using your current existing payment method. Please update your payment information to complete your donation{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with donations_full_url=donations_url|site_rel_url%}<a href="{{donations_full_url}}" target="_blank" rel="noopener noreferrer">Update payment method</a>{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">
    {% blocktrans with org_contact_email='org_contact_email'|site_settings %}Please contact us at <a href="mailto:{{ org_contact_email }}">{{ org_contact_email }}</a> for any enquiries.{% endblocktrans %}
</p>
<p style="{{ 'parag'|email_css }}">{% trans "Thank you," %}</p>

<p style="{{ 'parag'|email_css }}">{{ 'short_org_name'|site_settings }}</p>
{% endblock %}