django-app/donations/urls.py
from django.urls import path

from donations import views
from donations.payment_gateways._2c2p.views import verify_2c2p_response, return_from_2c2p
from donations.payment_gateways.stripe.views import create_checkout_session, verify_stripe_response, return_from_stripe, cancel_from_stripe, return_from_stripe_card_update, cancel_from_stripe_card_update
from donations.payment_gateways.paypal.views import create_paypal_transaction, verify_paypal_response, capture_paypal_order, return_from_paypal, cancel_from_paypal, cancel_from_paypal_card_update, return_from_paypal_card_update
from donations.payment_gateways.paypal_legacy.views import verify_paypal_legacy_response

app_name = 'donations'
urlpatterns = [
    path('donate/', views.donate, name='donate'),
    path('register-signin/', views.register_signin, name='register-signin'),
    path('confirm-donation/', views.confirm_donation, name='confirm-donation'),
    # path('donation-details/', views.donation_details, name='donation-details'),
    path('edit-recurring/<int:id>/', views.edit_recurring, name='edit-recurring'),
    path('toggle-recurring/', views.toggle_recurring, name='toggle-recurring'),
    path('cancel-recurring/', views.cancel_recurring, name='cancel-recurring'),
    path('dismiss-warning/', views.dismiss_warning, name='dismiss-warning' ),
    # path('verify-2c2p-response/', verify_2c2p_response, name='verify-2c2p-response'),
    # path('return-from-2c2p/', return_from_2c2p, name='return-from-2c2p'),
    path('create-stripe-session/', create_checkout_session, name='create-stripe-session'),
    path('verify-stripe-response/', verify_stripe_response, name='verify-stripe-response'),
    path('return-from-stripe/', return_from_stripe, name='return-from-stripe'),
    path('return-from-stripe-card-update/', return_from_stripe_card_update, name='return-from-stripe-card-update'),
    path('cancel-from-stripe/', cancel_from_stripe, name='cancel-from-stripe'),
    path('cancel-from-stripe-card-update/', cancel_from_stripe_card_update, name='cancel-from-stripe-card-update'),
    path('create-paypal-transaction/', create_paypal_transaction, name='create-paypal-transaction'),
    path('return-from-paypal/', return_from_paypal, name='return-from-paypal'),
    path('return-from-paypal-card-update/', return_from_paypal_card_update, name='return-from-paypal-card-update'),
    path('cancel-from-paypal/', cancel_from_paypal, name='cancel-from-paypal'),
    path('cancel-from-paypal-card-update/', cancel_from_paypal_card_update, name='cancel-from-paypal-card-update'),
    path('verify-paypal-response/', verify_paypal_response, name='verify-paypal-response'),
    path('verify-paypal-legacy-response/', verify_paypal_legacy_response, name='verify-paypal-legacy-response'),
    path('thank-you/', views.thank_you, name='thank-you'),
    path('cancelled/', views.cancelled, name='cancelled'),
    path('revoked/', views.revoked, name='revoked'),
    path('my-onetime-donations/', views.my_onetime_donations, name='my-onetime-donations'),
    path('my-recurring-donations/', views.my_recurring_donations, name='my-recurring-donations'),
    path('my-renewals/<uuid:uuid>/', views.my_renewals, name='my-renewals'),
    path('confirm-update-card-details/<int:id>/', views.confirm_update_card_details, name='confirm-update-card-details'),
    path('export-donations/', views.export_donations, name='export-donations'),
    path('export-subscriptions', views.export_subscriptions, name='export-subscriptions'),
    path('export-donors/', views.export_donors, name='export-donors')
]

django-app/newstream/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

from wagtailautocomplete.urls.admin import urlpatterns as autocomplete_admin_urls

from django.urls import include, path, re_path
import newstream.views as user_views
from . import gcsmedia

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/autocomplete/', include(autocomplete_admin_urls)),
    path('admin/', include(wagtailadmin_urls)),
    path('maintenance/', user_views.maintenance, name='maintenance'),
    # Media Server
    re_path('^gcsmedia/(?P<path>\S+)', gcsmedia.gcsmedia, name='gcsmedia')
]

urlpatterns += i18n_patterns(
    path('documents/', include(wagtaildocs_urls)),

    # path('search/', search_views.search, name='search'),

    path('donations/', include('donations.urls')),

    path('accounts/', include('allauth.urls')),

    path('personal-info/', user_views.personal_info, name='personal-info'),
    path('security/', user_views.security, name='security'),
    path('advanced-settings/', user_views.advanced_settings,
         name='advanced-settings'),
    path('advanced-settings/delete-account/', user_views.delete_account,
         name='delete-account'),
    path('unsubscribe/<email>/<hash>/', user_views.unsubscribe,
         name='unsubscribe'),

    # Export urls
    path('export-data/', user_views.download_export_data),
    path('export-data/donation', user_views.export_donation_data, name='export-donation-data'),
    path('export-data/subscription', user_views.export_subscription_data, name='export-subscription-data'),
    path('export-data/donor', user_views.export_donor_data, name='export-donor-data'),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    re_path(r'', include(wagtail_urls)),
)

django-app/newstream/views.py
import json
import csv
from datetime import datetime, timezone
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import logout, get_user_model
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import PermissionDenied
from django.conf import settings
from django.utils import translation

from donations.models import SubscriptionInstance, Donation, STATUS_ACTIVE, STATUS_PROCESSING, STATUS_PAUSED
from donations.email_functions import sendAccountDeletedNotifToAdmins, sendAccountDeletedNotifToDonor
from newstream.functions import generateIDSecretHash, process_user_meta
from newstream.forms import PersonalInfoForm, DeleteAccountForm
User = get_user_model()


def maintenance(request):
    return render(request, 'maintenance.html')


def unsubscribe(request, email, hash):
    failure = False
    try:
        user = User.objects.get(email=email)
        # check hash validity
        generated_hash = generateIDSecretHash(user.id)
        if hash == generated_hash:
            user.opt_in_mailing_list = False
            user.save()
        else:
            failure = True
    except Exception as e:
        print(str(e), flush=True)
        failure = True
    return render(request, 'unsubscription.html', {'failure': failure, 'email': email})


@login_required
def personal_info(request):
    if request.method == 'POST':
        form = PersonalInfoForm(request.POST, user=request.user)
        if form.is_valid():
            # process meta data
            user_metas = process_user_meta(request.POST)

            # process the data in form.cleaned_data as required
            user = request.user
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.opt_in_mailing_list = form.cleaned_data['opt_in_mailing_list']
            user.language_preference = form.cleaned_data['language_preference']
            translation.activate(user.language_preference)
            request.LANGUAGE_CODE = translation.get_language()
            user.metas = user_metas
            user.save()
            messages.add_message(request, messages.SUCCESS,
                                 _('Personal Info Updated.'))

            response = redirect('personal-info')
            response.set_cookie(
                settings.LANGUAGE_COOKIE_NAME, user.language_preference)
            return response
    else:
        form = PersonalInfoForm(user=request.user)
    return render(request, 'profile_settings/personal_info.html', {'form': form})


@login_required
def security(request):
    return render(request, 'profile_settings/security.html')


@login_required
def advanced_settings(request):
    # check if user can delete account or not
    cannot_delete_text = _('You need to cancel all your recurring donations before you are allowed to delete your account.')
    subs = SubscriptionInstance.objects.filter(user=request.user, recurring_status__in=[STATUS_ACTIVE, STATUS_PAUSED, STATUS_PROCESSING], deleted=False)
    if len(subs) > 0:
        deletable = False
    else:
        deletable = True
    return render(request, 'profile_settings/advanced_settings.html', {'deletable': deletable, 'cannot_delete_text': cannot_delete_text})


@login_required
def delete_account(request):
    if request.method == 'POST':
        form = DeleteAccountForm(request.POST)
        if form.is_valid():
            user = request.user
            # email notifications
            sendAccountDeletedNotifToAdmins(user)
            sendAccountDeletedNotifToDonor(user)

            # proceed to logout user
            # lastly, deletes the account
            logout(request)
            user.delete()
            messages.add_message(request, messages.SUCCESS,
                                 _('Your account is deleted.'))
            return redirect('/')
    else:
        form = DeleteAccountForm()
    return render(request, 'profile_settings/delete_account.html', {'form': form, 'confirm_text': DeleteAccountForm.CONFIRM_TEXT})

@login_required
def download_export_data(request):
    if not request.user.is_staff:
        raise PermissionDenied
    return render(request, 'export_data.html')

@login_required
def export_donation_data(request):
    """
    This function is the same as the other export function on the admin site, the main difference is this
    one does not have any PII on the data
    """
    if not request.user.is_staff:
        raise PermissionDenied
    filename = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S") + 'donation_data.csv'
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=' + filename

    # Include only fields that do not have a PII
    headings1 = ['id', 'transaction_id','donation_amount', 'is_recurring', 'currency', 'payment_status']
    headings2 = ['linked_user_deleted', 'gateway', 'subscription_id']
    headings3 = ['user_id', 'created_at', 'updated_at', 'donation_date',]
    donations = Donation.objects.all().select_related('user').select_related('gateway')
    headings =  headings1 + headings2 + headings3

    writer = csv.writer(response)
    writer.writerow(headings)

    for donation in donations:
        data_row = [getattr(donation, field) for field in headings1]
        data_row += [getattr(donation, field) for field in headings2]

        if donation.user is None:
            data_row += ['']
        else:
            data_row += [donation.user.id]

        created_at = getattr(donation, 'created_at').strftime("%Y-%m-%d %H:%M:%S")
        updated_at = getattr(donation, 'updated_at').strftime("%Y-%m-%d %H:%M:%S")
        donation_date = getattr(donation, 'donation_date').strftime("%Y-%m-%d")
        data_row += [created_at, updated_at, donation_date]

        writer.writerow(data_row)

    return response

@login_required
def export_subscription_data(request):
    """
    This function is the same as the other export function on the admin site, the main difference is this
    one does not have any PII on the data
    """
    if not request.user.is_staff:
        raise PermissionDenied
    filename = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S") + 'subscriptions.csv'
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=' + filename

    headings1 = ['id', 'profile_id','recurring_amount', 'currency', 'recurring_status']
    headings2 = ['linked_user_deleted', 'gateway']
    headings3 = ['user_id', 'created_at', 'updated_at', 'subscribe_date']
    subscriptions = SubscriptionInstance.objects.all().select_related('user').select_related('gateway')
    headings =  headings1 + headings2 + headings3

    writer = csv.writer(response)
    writer.writerow(headings)
    for subscription in subscriptions:
        data_row = [getattr(subscription, field) for field in headings1]
        data_row += [getattr(subscription, field) for field in headings2]

        if subscription.user is None:
            data_row += ['']
        else:
            data_row += [subscription.user.id]

        created_at = getattr(subscription, 'created_at').strftime("%Y-%m-%d %H:%M:%S")
        updated_at = getattr(subscription, 'updated_at').strftime("%Y-%m-%d %H:%M:%S")
        subscribe_date = getattr(subscription, 'subscribe_date').strftime("%Y-%m-%d")

        data_row += [created_at, updated_at, subscribe_date]

        writer.writerow(data_row)

    return response

@login_required
def export_donor_data(request):
    """
    This function is the same as the other export function on the admin site, the main difference is this
    one does not have any PII on the data
    """
    if not request.user.is_staff:
        raise PermissionDenied
    filename = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S") + 'donors.csv'
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=' + filename

    donors = User.objects.all()
    headings1 = ['id', 'is_active']
    headings2 = ['date_joined']
    headings = headings1 + headings2

    writer = csv.writer(response)
    writer.writerow(headings)
    for donor in donors:
        data_row = ([getattr(donor, field) for field in headings1])
        date_joined = getattr(donor, 'date_joined').strftime("%Y-%m-%d %H:%M:%S")
        data_row += [date_joined]
        writer.writerow(data_row)
    guests = Donation.objects.order_by().values_list('guest_email', flat=True).distinct()
    for guest in guests:
        if guest:
            writer.writerow(['GUEST','',''])
    return response

django-app/newstream/templates/base.html
{% load static wagtailuserbar common_tags wagtailimages_tags wagtailmetadata_tags %}
{% image 'site_icon'|site_settings max-32x32 as site_icon %}

<!DOCTYPE html>
<html class="no-js" lang="{{ request.LANGUAGE_CODE }}">

<head>
    <meta charset="utf-8" />
    <title>
        {% block title %}
        {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
        {% endblock %}
    </title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/png" sizes="32x32" href="{{ site_icon.url }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ site_icon.url }}">

    {# preload key requests #}
    <link rel="preload" href="/static/css/ttf/Barlow-SemiBold.ttf" type="font/ttf" as="font" crossorigin="anonymous">
    <link rel="preload" href="/static/css/ttf/Barlow-Regular.ttf" type="font/ttf" as="font" crossorigin="anonymous">
    <link rel="preload" href="/static/css/ttf/FiraSans-SemiBold.ttf" type="font/ttf" as="font" crossorigin="anonymous">
    <link rel="preload" href="/static/css/ttf/FiraSans-Regular.ttf" type="font/ttf" as="font" crossorigin="anonymous">

    {# Global stylesheets #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main_1_20.css' %}">

    {# wagtail-metadata: only wagtail pages in the page tree have the self object to be pulled from, this is not for other pages defined in the urls.py #}
    {% if self != None %}
    {% meta_tags %}
    {% endif %}

    {% include "common/datadog.html" %}

    {% block extra_head %}
    {# Override this in templates to add extra stuff in the head #}
    {% endblock %}
</head>

<body class="{% block body_class %}{% endblock %}">
    <div class="cover"></div>

    {% wagtailuserbar %}

    {% include "header.html" %}

    <div id="base-content-wrapper">
        {% include "mobile_messages.html" %}
        {% block content %}{% endblock %}
    </div>

    {% include "footer.html" %}

    {# Global javascript #}
    <script type="text/javascript" src="{% static 'js/main_1_5.js' %}"></script>

    {% block extra_js %}
    {# Override this in templates to add extra javascript #}
    {% endblock %}
</body>

</html>

django-app/newstream/templates/base_email.html
{% load static common_tags wagtailimages_tags %}
{% image 'brand_logo'|site_settings max-120x120 as brand_logo %}
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {# Don't include styles in head section : https://css-tricks.com/using-css-in-html-emails-the-real-story/ #}
</head>
<body>
    <div style="background-color:#e7edef;min-width:100%!important;width:100%;font-family:Arial,Helvetica;font-size:14px;line-height:1.4;margin:0;padding:0">
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;width:100%">
            <tbody>
                <tr>
                    <td style="font-family:Arial,Helvetica;font-size:14px;vertical-align:top;display:block;margin:0 auto;padding:25px 0 30px;max-width:500px;width:100%;min-width:320px">
                        <div style="box-sizing:border-box;display:block;Margin:0 auto">
                            <table style="border-collapse:separate;width:100%;text-align:left">
                                <tbody>
                                    <tr height="15px">
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <img src="{{ brand_logo.url|site_rel_url }}" alt="{{ brand_logo.alt }}" width="{{ brand_logo.width }}" height="{{ brand_logo.height }}">
                                        </td>
                                    </tr>
                                    <tr height="15px">
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>
                            <table cellspacing="0" cellpadding="0" style="border-top:1px solid #dcdcdc;border-collapse:separate;width:100%;background:#ffffff">
                                <tbody>
                                    <tr>
                                        <td style="font-family:Arial,Helvetica;font-size:14px;vertical-align:top;box-sizing:border-box;padding:24px">
                                            <table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;width:100%">
                                                <tbody>
                                                    <tr>
                                                        <td style="font-family:Arial,Helvetica;font-size:14px;vertical-align:top">
                                                        {% block content %}{% endblock %}
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>

</html>

django-app/newstream/templates/export_data.html
{% extends "modeladmin/index.html" %}
{% block title %}Download data{% endblock %}

{% block content %}
<div class="nice-padding">
    <h1>Download data</h1>
    <p>
        <a href="{% url 'export-donation-data' %}" class="button block">
            Donation
        </a>
    </p>
    <p>
        <a href="{% url 'export-subscription-data' %}" class="button block">
            Subscription
        </a>
    </p>
    <p>
        <a href="{% url 'export-donor-data' %}" class="button block">
            Donors
        </a>
    </p>
</div>
{% endblock %}

django-app/newstream/templates/footer.html
{% load common_tags wagtailcore_tags wagtailimages_tags i18n %}
{% image 'brand_logo'|site_settings max-80x80 as brand_logo %}

<div class='newstream-footer md:items-center'>
    <a href="{% pageurl homepage %}" class="brand-logo-link">
        <img src="{{ brand_logo.url }}" alt="{{ brand_logo.alt }}" width="{{ brand_logo.width }}"
            height="{{ brand_logo.height }}">
    </a>
    <div class="site-links mb-2">
        <a href="{{ privacy_policy_link }}" target="_blank" rel="noopener noreferrer">{% trans 'Privacy Policy' %}</a>
    </div>
    <div class="site-copyright-text flex md:justify-center md:items-center flex-col md:flex-row">
        <span>{% blocktrans %}© 2020 Hong Kong Free Press Limited.</span><span>&nbsp;Part of <a href="https://github.com/diffractive/newstream" target="_blank"
                class="pl-1">The
                NewStream
                Project</a>.{% endblocktrans %}</span>
    </div>
</div>

django-app/newstream/templates/header.html
{% load i18n common_tags wagtailcore_tags wagtailimages_tags %}
{% image 'brand_logo'|site_settings max-120x120 as brand_logo %}

{% include "common/mobile_main_menu.html" %}
<div id="newstream-header" class='z-50 bg-transparent fixed'>
    <div id="newstream-topnav"
        class="flex justify-end lg:justify-between items-center w-screen bg-white py-6 px-8 lg:py-10 lg:px-10 xl:px-16">
        <div class="flex items-center lg:pr-8">
            <div id="nav-toggle" name="nav-menu" class="lg:hidden focus:outline-none cursor-pointer">
                <span></span>
                <span></span>
                <span></span>
            </div>
            {% include "common/main_menu.html" %}
        </div>
        <a href="{% pageurl homepage %}" class="brand-logo-link">
            <img src="{{ brand_logo.url }}" alt="{{ brand_logo.alt }}" width="{{ brand_logo.width }}"
                height="{{ brand_logo.height }}">
        </a>
        <div class="items-center justify-end pl-8 hidden lg:flex">
            {% if user.is_authenticated %}
            <div class="nav-user-dropdown-div mr-6 hidden lg:flex items-center dropdown-div-wrapper">
                <input type="checkbox" name="dropdown-toggle-checkbox" id="dropdown-toggle-checkbox"
                    class="dropdown-toggle-checkbox">
                <label for="dropdown-toggle-checkbox" class="dropdown-toggle-label"></label>
                <span class="avatar-icon"></span>
                <span class="user-fullname">{{ user|display_username }}</span>
                <span class="dropdown-chevron-icon"></span>
                <div class="user-dropdown-menu dropdown-menu-popup flex flex-col items-stretch">
                    <a id="header-settings" href="{% url 'personal-info' %}">{% trans 'Profile Settings' %}</a>
                    <a id="header-donations" href="{% url 'donations:my-onetime-donations' %}">{% trans 'My Donations' %}</a>
                    <a id="header-logout" href="{% url 'account_logout' %}">{% trans 'Logout' %}</a>
                </div>
            </div>
            {% else %}
            <a id="header-sign-in" href="{% url 'account_login' %}{{ request.path|next_path_filter }}" class="mr-16 menu-item">{% trans 'Sign in' %}</a>
            {% endif %}
            <a href="{% url 'donations:donate'%}" class="menu-item nav-donate-btn">{% trans 'Donate' %}</a>
            <div class="multilang-dropdown-div ml-6 hidden lg:hidden items-center dropdown-div-wrapper">
                {% include 'common/lang_switcher_body.html' with prefix='main' %}
            </div>
        </div>
    </div>
    {% include "messages.html" %}
</div>

django-app/newstream/templates/maintenance.html
{% extends "base.html" %}
{% load i18n %}

{% block body_class %}template-maintenance{% endblock %}

{% block title %}{% trans 'Site Under Maintenance' %}{% endblock %}

{% block content %}
<div class="container-tight flex flex-col items-start lg:items-center">
    <h1 class="mb-5">{% trans 'Site Under Maintenance' %}</h1>
    <h4>{% trans "Sorry for the inconvenience but we're performing maintenance at the moment. We'll be back online shortly!" %}</h4>
</div>
{% endblock %}

django-app/newstream/templates/messages.html
{% load common_tags i18n %}

{% if messages %}
<div class="z-50 pt-4 pr-4 hidden sm:block" id="messages-wrapper">
    <div class="messages flex flex-col items-end bg-transparent">
        {% for message in messages %}
        <div class="message max-width-500 p-4 {% if message.tags %}{{ message.tags|alert_class }}{% endif %} {{ message.extra_tags }}">
            <p class="font-bold lg:text-center m-0">{{ message }}</p>
            {% if "cta-manage-donations" in message.extra_tags %}
            <button class="ns-wide-btn right-arrow-btn bg-danger" type="button" id="cta-manage-donations" onclick="location.href='{% url "donations:my-recurring-donations" %}'">
                {% trans 'Manage recurring donations' %}<span class="icon"></span>
            </button>
            {% elif "cta-new-donation" in message.extra_tags %}
            <button class="ns-wide-btn right-arrow-btn bg-danger" type="button" id="cta-new-donation" onclick="location.href='{% url "donations:donate" %}'">
                {% trans 'Make new donation' %}<span class="icon"></span>
            </button>
            {% elif "cta-update-card" in message.extra_tags %}
            <button class="ns-wide-btn right-arrow-btn bg-warning" type="button" id="cta-update-card" onclick="location.href='{% url "donations:confirm-update-card-details" request.session.sub_instance_id %}'">
                {% trans 'Update payment method' %}<span class="icon"></span>
            </button>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

django-app/newstream/templates/mobile_messages.html
{% load common_tags i18n %}

{% if messages %}
<div class="sm:hidden" id="messages-wrapper">
    <div class="messages flex flex-col items-end bg-transparent">
        {% for message in messages %}
        <div class="message w-screen p-4 {% if message.tags %}{{ message.tags|alert_class }}{% endif %} {{ message.extra_tags }}">
            <p class="font-bold lg:text-center m-0">{{ message }}</p>
            {% if "cta-manage-donations" in message.extra_tags %}
            <button class="ns-wide-btn right-arrow-btn bg-danger" type="button" onclick="location.href='{% url "donations:my-recurring-donations" %}'">
                {% trans 'Manage recurring donations' %}<span class="icon"></span>
            </button>
            {% elif "cta-new-donation" in message.extra_tags %}
            <button class="ns-wide-btn right-arrow-btn bg-danger" type="button" onclick="location.href='{% url "donations:donate" %}'">
                {% trans 'Make new donation' %}<span class="icon"></span>
            </button>
            {% elif "cta-update-card" in message.extra_tags %}
            <button class="ns-wide-btn right-arrow-btn bg-warning" type="button" onclick="location.href='{% url "donations:confirm-update-card-details" request.session.sub_instance_id %}'">
                {% trans 'Update payment method' %}<span class="icon"></span>
            </button>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

django-app/newstream/templates/unsubscription.html
{% extends 'base.html' %}
{% load common_tags widget_tweaks i18n %}

{% block title %}{% blocktrans with sitename=''|site_name_filter %}Unsubscribe from
{{ sitename }}{% endblocktrans %}{% endblock %}

{% block content %}
<div class="container-tight flex flex-col items-center">
    {% if failure %}
    <h1 class="mb-5 text-center">{% trans 'Failed to unsubscribe' %}</h1>
    <p class="text-center mb-5">{% blocktrans %}We failed to unsubscribe you <span class="font-bold">({{email}})</span>
        from us, your
        unsubscription link is invalid.{% endblocktrans %}
    </p>
    {% else %}
    <h1 class="mb-5 text-center">{% trans 'Successful' %}</h1>
    <p class="text-center mb-5">{% blocktrans %}You <span class="font-bold">({{email}})</span> have unsubscribed from
        us. You can
        subscribe back to us anytime you like
        by checking the opt in mailing box in your personal info settings.{% endblocktrans %}
    </p>
    {% endif %}
</div>
{% endblock %}